### ISSUE TITLE
Add possibility to auto-export the output to the file system

### ISSUE THREAD

**Issue by LeHack** [firebug/consoleexport#9]
I needed to use consoleexport with automated selenium/webdriver tests and wanted it to write the logs to a file (in append mode), but do it automatically (like it does when sending to the specified upload server) instead of when clicking 'save as'.
Here you can find my solution as a patch to apply with consoleExport-0.5b5 http://code.google.com/p/fbug/issues/detail?id=5182#c17

Hope anybody finds it useful :)

PS. Remember, that to make it work with selenium tests, you need to add it to your profile along with Firebug, and then set the console tab open by default (otherwise it's inactive and no logs are written).

**Comment by SebastianZ** [comment]
@LeHack Maybe you could create a pull request for your patch, so it can be applied?

Sebastian

**Comment by LeHack** [comment]
Sure, I just have to review it whether it still applies cleanly on the current master.
But wasn't there something similar already added to consoleexport? I'll check when I have a moment and if not, I'll prepare the PR.

**Comment by SebastianZ** [comment]
Ah, you're right. Your patch was applied in https://github.com/firebug/consoleexport/commit/22bddbd9170788e09a88d33d357ab1a9fc84eb56.

There's just no new release yet, as far as I can see.

Sebastian
